"""add_notification_event_model

Revision ID: 7b48b4340479
Revises: a4def820a5bb
Create Date: 2021-04-06 14:16:50.069846+00:00

"""
from alembic import op
import sqlalchemy as sa
from faraday.server.fields import JSONType
from depot.fields.sqlalchemy import UploadedFileField


# revision identifiers, used by Alembic.
revision = '7b48b4340479'
down_revision = '064f8fa9f999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('notification_data', JSONType(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # Added manually
    op.add_column('notification_event',
                  sa.Column(
                      'event',
                      sa.Enum('new_workspace', 'new_agent', 'new_user', 'new_agent_scan', 'new_report_scan', 'new_vulnerability', name='notification_events'),
                      nullable=True
                  )
    )

    op.add_column('notification_event',
        sa.Column(
            'object_type',
            sa.Enum('vulnerability', 'host', 'credential', 'service', 'source_code', 'comment', 'executive_report',
                    'workspace', 'task', name='object_types'),
            nullable=False
        )
    )

    op.create_table('notification_sent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('notification_subscription_config_id', sa.Integer(), nullable=False),
    sa.Column('mark_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['notification_event.id'], ),
    sa.ForeignKeyConstraint(['notification_subscription_config_id'], ['notification_subscription_base_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_sent_event_id'), 'notification_sent', ['event_id'], unique=False)
    op.create_index(op.f('ix_notification_sent_mark_read'), 'notification_sent', ['mark_read'], unique=False)
    op.create_index(op.f('ix_notification_sent_notification_subscription_config_id'), 'notification_sent', ['notification_subscription_config_id'], unique=False)
    op.drop_column('action', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_notification_sent_notification_subscription_config_id'), table_name='notification_sent')
    op.drop_index(op.f('ix_notification_sent_mark_read'), table_name='notification_sent')
    op.drop_index(op.f('ix_notification_sent_event_id'), table_name='notification_sent')
    op.drop_table('notification_sent')
    op.drop_table('notification_event')
    # ### end Alembic commands ###
