#!/bin/bash
###
## Faraday Penetration Test IDE - Community Version
## Copyright (C) 2013  Infobyte LLC (http://www.infobytesec.com/)
## See the file 'doc/LICENSE' for the license information
###

#faraday update v0.1
find -name "*pyc" -delete
git pull
