#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
Faraday Penetration Test IDE
Copyright (C) 2013  Infobyte LLC (http://www.infobytesec.com/)
See the file 'doc/LICENSE' for the license information
'''

from __future__ import with_statement
from plugins import core
from model import api
import re
import os
import sys

try:

    import xml.etree.cElementTree as ET
    import xml.etree.ElementTree as ET_ORIG
    ETREE_VERSION = ET_ORIG.VERSION
except ImportError:
    import xml.etree.ElementTree as ET
    ETREE_VERSION = ET.VERSION

ETREE_VERSION = [int(i) for i in ETREE_VERSION.split('.')]

current_path = os.path.abspath(os.getcwd())

__author__     = 'Francisco Amato'
__copyright__  = 'Copyright (c) 2013, Infobyte LLC'
__credits__    = ['Francisco Amato']
__license__    = ''
__version__    = '1.0.0'
__maintainer__ = 'Francisco Amato'
__email__      = 'famato@infobytesec.com'
__status__     = 'Development'

class QualysguardXmlParser(object):
    """
    The objective of this class is to parse an xml file generated by the qualysguard tool.

    TODO: Handle errors.
    TODO: Test qualysguard output version. Handle what happens if the parser doesn't support it.
    TODO: Test cases.

    @param qualysguard_xml_filepath A proper xml generated by qualysguard
    """
    def __init__(self, xml_output):

        tree = self.parse_xml(xml_output)
        if tree:
            self.items = [data for data in self.get_items(tree)]
        else:
            self.items = []

    def parse_xml(self, xml_output):
        """
        Open and parse an xml file.

        TODO: Write custom parser to just read the nodes that we need instead of
        reading the whole file.

        @return xml_tree An xml tree instance. None if error.
        """
        try:
            tree = ET.fromstring(xml_output)
        except SyntaxError, err:
            self.devlog('SyntaxError: %s. %s' % (err, xml_output))
            return None

        return tree

    def get_items(self, tree):
        """
        @return items A list of Host instances
        """
        for node in tree.find('HOST_LIST').findall('HOST'):
            yield Item(node, tree)


class Item(object):
    """
    An abstract representation of a Item (HOST)
    @param item_node A item_node taken from an qualysguard xml tree
    """
    def __init__(self, item_node, tree):

        self.node = item_node
        self.ip = self.get_text_from_subnode('IP')

        self.os = self.get_text_from_subnode('OPERATING_SYSTEM')
        self.vulns = self.getResults(tree)

    def getResults(self, tree):

        glossary = tree.find('GLOSSARY/VULN_DETAILS_LIST')

        for self.issue in self.node.find('VULN_INFO_LIST'):
            yield Results(self.issue, glossary)

    def get_text_from_subnode(self, subnode_xpath_expr):
        """
        Finds a subnode in the host node and the retrieves a value from it.

        @return An attribute value
        """
        sub_node = self.node.find(subnode_xpath_expr)
        if sub_node is not None:
            return sub_node.text

        return None


class Results():

    def __init__(self, issue_node, glossary):

        #VULN_INFO ElementTree
        self.node = issue_node
        self.port = self.get_text_from_subnode(self.node, 'PORT')
        self.protocol = self.get_text_from_subnode(self.node, 'PROTOCOL')
        self.name = self.get_text_from_subnode(self.node, 'QID')
        self.result = self.get_text_from_subnode(self.node, 'RESULT')

        self.severity_dict = {
        None : 'info',
        '' : 'info',
        '1' : 'low',
        '2' : 'med',
        '3' : 'high'
        }

        #GLOSSARY TAG
        self.glossary = glossary
        self.severity = self.severity_dict[self.get_text_from_glossary('SEVERITY')]
        self.title = self.get_text_from_glossary('TITLE')
        self.cvss = self.get_text_from_glossary('CVSS_SCORE/CVSS_BASE')
        self.pci = self.get_text_from_glossary('PCI_FLAG')
        self.solution = self.get_text_from_glossary('SOLUTION')
        self.impact = self.get_text_from_glossary('IMPACT')

        #Description
        self.desc = self.cleaner_results(self.get_text_from_glossary('THREAT'))
        if not self.desc:
            self.desc = ''
        if self.result:
            self.desc += '\n\nResult: ' + self.cleaner_results(self.result)
        if self.impact:
            self.desc += '\n\nImpact: ' +self.cleaner_results(self.impact)
        if self.result:
            self.desc += '\n\nSolution: ' + self.cleaner_results(self.solution)

        #References
        self.ref = []
        self.ref.append( self.get_text_from_glossary('CVE_ID_LIST/CVE_ID/ID') )

        if self.cvss:
            self.ref.append('CVSS SCORE: ' + self.cvss)

        if self.pci:
            self.ref.append('PCI: ' + self.pci)

    def cleaner_results(self, string):

        return string.replace('<P>', '').replace('<UL>','').replace('<LI>','').replace('<BR>', '')

    def get_text_from_glossary(self, tag):
        """
        Finds a subnode in the glossary and retrieves a value of this.
        Filter by QualysId.

        @return An attribute value
        """

        for vuln_detail in self.glossary:

            id_act = vuln_detail.get('id').strip('qid_')
            if id_act == self.name:

                text = vuln_detail.find(tag)
                if text is not None:
                    return text.text
                else:
                    return None

    def get_text_from_subnode(self, node, subnode_xpath_expr):
        """
        Finds a subnode in the node and the retrieves a value from it.

        @return An attribute value
        """
        sub_node = node.find(subnode_xpath_expr)
        if sub_node is not None:
            return sub_node.text

        return None

class QualysguardPlugin(core.PluginBase):
    """
    Example plugin to parse qualysguard output.
    """
    def __init__(self):

        core.PluginBase.__init__(self)
        self.id              = 'Qualysguard'
        self.name            = 'Qualysguard XML Output Plugin'
        self.plugin_version         = '0.0.2'
        self.version   = 'Qualysguard 2016 March '
        self.framework_version  = '1.0.0'
        self.options         = None
        self._current_output = None
        self._command_regex  = re.compile(r'^(sudo qualysguard|\.\/qualysguard).*?')

        global current_path
        self._output_file_path = os.path.join(self.data_path,
                                             'qualysguard_output-%s.xml' % self._rid)

    def parseOutputString(self, output, debug = False):

        parser = QualysguardXmlParser(output)

        for item in parser.items:

            h_id = self.createAndAddHost(
            item.ip,
            item.os
            )

            i_id = self.createAndAddInterface(
            h_id,
            item.ip,
            ipv4_address = item.ip,
            hostname_resolution = item.ip
            )

            for v in item.vulns:

                if v.port is None:

                    v_id = self.createAndAddVulnToHost(
                    h_id,
                    v.title if v.title else v.name,
                    ref = v.ref,
                    severity = v.severity,
                    resolution = v.solution if v.solution else '',
                    desc = v.desc
                    )

                else:

                    web = False
                    s_id = self.createAndAddServiceToInterface(
                    h_id,
                    i_id,
                    v.port,
                    v.protocol,
                    ports = [ str(v.port) ],
                    status = 'open'
                    )

                    if v.port in ['80','443'] or re.search('ssl|http', v.name):
                        web = True
                    else:
                        web = False

                    if web:
                        v_id = self.createAndAddVulnWebToService(
                        h_id,
                        s_id,
                        v.title if v.title else v.name,
                        ref = v.ref,
                        website = item.ip,
                        severity = v.severity,
                        desc = v.desc,
                        resolution = v.solution if v.solution else ''
                        )

                        n_id = self.createAndAddNoteToService(
                        h_id,
                        s_id,
                        'website',
                        ''
                        )

                        n2_id = self.createAndAddNoteToNote(
                        h_id,
                        s_id,
                        n_id,
                        item.ip,
                        ''
                        )

                    else:
                        v_id = self.createAndAddVulnToService(
                        h_id,
                        s_id,
                        v.title if v.title else v.name,
                        ref = v.ref,
                        severity = v.severity,
                        desc = v.desc,
                        resolution = v.solution if v.solution else ''
                        )

        del parser

    def processCommandString(self, username, current_path, command_string):
        return None

    def setHost(self):
        pass

def createPlugin():
    return QualysguardPlugin()

if __name__ == '__main__':
    parser = QualysguardXmlParser(sys.argv[1])
    for item in parser.items:
        if item.status == 'up':
            print item
