.set-remote-github:
  script:
    - git remote add github https://${GH_USER}:${GH_TOKEN}@github.com/infobyte/faraday.git


update_github:
    image: python:3
    stage: publish
    script:
      - !reference [.set-remote-github, script]
      - !reference [ .get_from_tar_and_replace_www, script ]
      - git add *
      - git commit -m "Front Updated"
      - git push github $CI_COMMIT_REF_NAME:$DESTINY_BRANCH
    rules:
      - if: '$CI_COMMIT_REF_NAME == "white/master"'
        variables:
          DESTINY_BRANCH: master
        when: on_success
#      - if: '$CI_COMMIT_REF_NAME == "white/staging"'
#        variables:
#          DESTINY_BRANCH: staging
#        when: on_success
    tags:
        - faradaytests
    needs:
      - project: faradaysec/faraday-react
        job: npm_build
        ref: community/master
        artifacts: true


tag_on_github:
    image: python:3
    stage: publish
    script:
      - !reference [.set-remote-github, script]
      - export FARADAY_VERSION=$(eval $IMAGE_TAG)
      - CHANGELOG/check_pre_tag.py
      - git tag v$FARADAY_VERSION -m "$(cat CHANGELOG/$FARADAY_VERSION/community.md)"
      - git push github v$FARADAY_VERSION
      - scripts/github_release.py --deb-file ./faraday-server_amd64.deb --rpm-file ./faraday-server_amd64.rpm
    rules:
      - !reference [ .on-community-tag, rules ]
    dependencies:
      - generate_deb_master
      - generate_rpm_master
    tags:
      - faradaytests
