"""Add warnings to command model

Revision ID: 1145efa88414
Revises: b5065f401599
Create Date: 2023-03-30 19:49:28.651868+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1145efa88414'
down_revision = 'b5065f401599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command', sa.Column('warnings', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('command', 'warnings')
    # ### end Alembic commands ###
