"""Add delete cascades from workspace

Revision ID: 1f552b18cbdb
Revises: a4def820a5bb
Create Date: 2021-04-05 19:11:53.866521+00:00

"""
from alembic import op
import sqlalchemy as sa
from faraday.server.fields import JSONType
from depot.fields.sqlalchemy import UploadedFileField


# revision identifiers, used by Alembic.
revision = '1f552b18cbdb'
down_revision = 'a4def820a5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('credential_workspace_id_fkey', 'credential', type_='foreignkey')
    op.create_foreign_key(None, 'credential', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('host_workspace_id_fkey', 'host', type_='foreignkey')
    op.create_foreign_key(None, 'host', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('hostname_workspace_id_fkey', 'hostname', type_='foreignkey')
    op.create_foreign_key(None, 'hostname', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('rule_action_uc', 'rule_action', type_='unique')
    op.drop_constraint('service_workspace_id_fkey', 'service', type_='foreignkey')
    op.create_foreign_key(None, 'service', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('vulnerability_workspace_id_fkey', 'vulnerability', type_='foreignkey')
    op.create_foreign_key(None, 'vulnerability', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vulnerability', type_='foreignkey')
    op.create_foreign_key('vulnerability_workspace_id_fkey', 'vulnerability', 'workspace', ['workspace_id'], ['id'])
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.create_foreign_key('service_workspace_id_fkey', 'service', 'workspace', ['workspace_id'], ['id'])
    op.create_unique_constraint('rule_action_uc', 'rule_action', ['rule_id', 'action_id'])
    op.drop_constraint(None, 'hostname', type_='foreignkey')
    op.create_foreign_key('hostname_workspace_id_fkey', 'hostname', 'workspace', ['workspace_id'], ['id'])
    op.drop_constraint(None, 'host', type_='foreignkey')
    op.create_foreign_key('host_workspace_id_fkey', 'host', 'workspace', ['workspace_id'], ['id'])
    op.drop_constraint(None, 'credential', type_='foreignkey')
    op.create_foreign_key('credential_workspace_id_fkey', 'credential', 'workspace', ['workspace_id'], ['id'])
    # ### end Alembic commands ###
