"""divide open for days

Revision ID: 27d7eff884e7
Revises: 34468fcfd92e
Create Date: 2024-04-29 16:35:30.590225+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d7eff884e7'
down_revision = '34468fcfd92e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_critical_enabled', sa.Boolean(), nullable=True, default=False, server_default='false'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_critical_app', sa.Boolean(), nullable=True, default=False, server_default='false'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_critical_email', sa.Boolean(), nullable=True, default=False, server_default='false'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_critical_slack', sa.Boolean(), nullable=True, default=False, server_default='false'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_critical', sa.Integer(), nullable=True, default=0, server_default='0'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_high_enabled', sa.Boolean(), nullable=True, default=False, server_default='false'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_high_app', sa.Boolean(), nullable=True, default=False, server_default='false'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_high_email', sa.Boolean(), nullable=True, default=False, server_default='false'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_high_slack', sa.Boolean(), nullable=True, default=False, server_default='false'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_high', sa.Integer(), nullable=True, default=0, server_default='0'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_medium_enabled', sa.Boolean(), nullable=True, default=False, server_default='false'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_medium_app', sa.Boolean(), nullable=True, default=False, server_default='false'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_medium_email', sa.Boolean(), nullable=True, default=False, server_default='false'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_medium_slack', sa.Boolean(), nullable=True, default=False, server_default='false'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_medium', sa.Integer(), nullable=True, default=0, server_default='0'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_low_enabled', sa.Boolean(), nullable=True, default=False, server_default='false'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_low_app', sa.Boolean(), nullable=True, default=False, server_default='false'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_low_email', sa.Boolean(), nullable=True, default=False, server_default='false'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_low_slack', sa.Boolean(), nullable=True, default=False, server_default='false'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_low', sa.Integer(), nullable=True, default=0, server_default='0'))
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_email')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_slack')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_app')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_enabled')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days', sa.INTEGER(), autoincrement=False, nullable=True, server_default='0'))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_app', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_slack', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('user_notification_settings', sa.Column('adv_vuln_open_days_email', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_low')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_low_slack')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_low_email')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_low_app')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_low_enabled')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_medium')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_medium_slack')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_medium_email')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_medium_app')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_medium_enabled')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_high')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_high_slack')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_high_email')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_high_app')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_high_enabled')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_critical')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_critical_slack')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_critical_email')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_critical_app')
    op.drop_column('user_notification_settings', 'adv_vuln_open_days_critical_enabled')
    # ### end Alembic commands ###
