"""severities histogram constraint

Revision ID: 443a136bb5f2
Revises: 33094e577642
Create Date: 2023-12-01 17:39:24.284436+00:00

"""
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '443a136bb5f2'
down_revision = '33094e577642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Fix duplicated histograms
    conn = op.get_bind()
    rows = conn.execute(text('SELECT '
               'SUM(medium) as medium, '
               'SUM(high) as high,'
               'SUM(critical) as critical, '
               'SUM(confirmed) as confirmed, '
               'workspace_id, '
               'date, '
               'COUNT(*) '
               'FROM severities_histogram '
               'group by '
               'workspace_id, '
               'date '
               'having COUNT(*) > 1'))
    for row in rows:
        conn.execute(
            text("DELETE FROM severities_histogram WHERE workspace_id = :workspace_id AND date = :date"),
            {"workspace_id": row[4], "date": row[5]},
        )
        conn.execute(
            text(
                "INSERT INTO severities_histogram "
                "(workspace_id, date, medium, high, critical, confirmed) "
                "VALUES (:workspace_id, :date, :medium, :high, :critical, :confirmed)"
            ),
            {
                "workspace_id": row[4],
                "date": row[5],
                "medium": row[0],
                "high": row[1],
                "critical": row[2],
                "confirmed": row[3],
            },
        )
    op.create_unique_constraint('uix_severities_histogram_table_date_workspace_id', 'severities_histogram',
                                ['date', 'workspace_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_severities_histogram_table_date_workspace_id', 'severities_histogram', type_='unique')
    # ### end Alembic commands ###
