"""Add host stats static columns

Revision ID: 51e533d41312
Revises: 257f6d0ad43f
Create Date: 2024-01-12 20:12:43.408035+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '51e533d41312'
down_revision = '257f6d0ad43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('vulnerability_critical_generic_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('host', sa.Column('vulnerability_high_generic_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('host', sa.Column('vulnerability_medium_generic_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('host', sa.Column('vulnerability_low_generic_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('host', sa.Column('vulnerability_info_generic_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('host', sa.Column('vulnerability_unclassified_generic_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host', 'vulnerability_unclassified_generic_count')
    op.drop_column('host', 'vulnerability_info_generic_count')
    op.drop_column('host', 'vulnerability_low_generic_count')
    op.drop_column('host', 'vulnerability_medium_generic_count')
    op.drop_column('host', 'vulnerability_high_generic_count')
    op.drop_column('host', 'vulnerability_critical_generic_count')
    # ### end Alembic commands ###
