"""Update risk value

Revision ID: 699402156cf4
Revises: 3eb96406e88d
Create Date: 2022-11-15 19:09:54.669437+00:00

"""

# revision identifiers, used by Alembic.
revision = '699402156cf4'
down_revision = '3eb96406e88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###
