"""agents category

Revision ID: 75c38da2da8a
Revises: 618a59151523
Create Date: 2025-01-27 20:36:41.962127+00:00

"""
from alembic import op
import sqlalchemy as sa
from faraday.server.fields import JSONType


# revision identifiers, used by Alembic.
revision = '75c38da2da8a'
down_revision = '618a59151523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_agent', sa.Column('category', JSONType(), nullable=True))
    op.add_column('executor', sa.Column('category', JSONType(), nullable=True))
    op.add_column('executor', sa.Column('tool', sa.String(length=50), nullable=True))
    op.add_column('agent_execution', sa.Column('triggered_by', sa.String(), nullable=True))
    op.add_column('cloud_agent_execution', sa.Column('triggered_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executor', 'tool')
    op.drop_column('executor', 'category')
    op.drop_column('cloud_agent', 'category')
    op.drop_column('cloud_agent_execution', 'triggered_by')
    op.drop_column('agent_execution', 'triggered_by')
    # ### end Alembic commands ###
