"""add fields to report

Revision ID: 97a9348d0406
Revises: f0439bf6688a
Create Date: 2021-06-03 18:36:28.695990+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression


# revision identifiers, used by Alembic.
revision = '97a9348d0406'
down_revision = 'f0439bf6688a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executive_report', sa.Column('duplicate_detection', sa.Boolean(), nullable=False,
                                                server_default=expression.false()))
    op.add_column('executive_report', sa.Column('border_size', sa.Integer(), nullable=False, server_default='3'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executive_report', 'border_size')
    op.drop_column('executive_report', 'duplicate_detection')
    # ### end Alembic commands ###
