"""Add host stats static columns

Revision ID: a87fa2478a1a
Revises: f7ca45632cce
Create Date: 2024-01-09 18:01:50.211125+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87fa2478a1a'
down_revision = 'f7ca45632cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('vulnerability_critical_generic_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host', 'vulnerability_critical_generic_count')
    # ### end Alembic commands ###
