"""update rule fields

Revision ID: aa56852fa76d
Revises: a4def820a5bb
Create Date: 2021-04-12 19:53:48.615218+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa56852fa76d'
down_revision = 'a4def820a5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('description', sa.String(), nullable=False))
    op.drop_constraint('condition_rule_id_fkey', 'condition', type_='foreignkey')
    op.create_foreign_key(None, 'condition', 'rule', ['rule_id'], ['id'], ondelete='CASCADE')
    op.add_column('rule', sa.Column('description', sa.String(), nullable=False))
    op.add_column('rule', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'rule', ['name'])
    op.drop_column('rule', 'object')
    op.create_unique_constraint('rule_action_uc', 'rule_action', ['rule_id', 'action_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rule_action_uc', 'rule_action', type_='unique')
    op.add_column('rule', sa.Column('object', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rule', type_='unique')
    op.drop_column('rule', 'name')
    op.drop_column('rule', 'description')
    op.drop_constraint(None, 'condition', type_='foreignkey')
    op.create_foreign_key('condition_rule_id_fkey', 'condition', 'rule', ['rule_id'], ['id'])
    op.drop_column('action', 'description')
    # ### end Alembic commands ###
