merge_conflict_check:
    tags:
        - faradaytests
    image: python:3.11
    stage: pre_testing
    script:
        - git config --global user.email "you@example.com"
        - git config --global user.name "Mergerbot"
        - python3 scripts/merge-conflict-detector.py
    rules:
        - !reference [ .ignore-on-tag, rules ]
        - when: on_success

sanity_check:
    tags:
        - faradaytests
    image: python:3.11
    stage: pre_testing
    script:
        - bash scripts/sanity_check_commit.sh
        - scripts/sanity_check_file.py --mode=ls
    rules:
        - !reference [ .dev-staging-master, rules ]
        - !reference [ .ignore-on-tag, rules ]
        - when: never

migration_sanity_check:
    tags:
        - faradaytests
    image: python:3.11
    stage: pre_testing
    script:
        - scripts/model_check.py
        - pip install .
        - cd faraday
        - $(alembic branches)
    rules:
        - !reference [ .dev-staging-master, rules ]
        - !reference [ .ignore-on-tag, rules ]
        - when: never

bandit:
    tags:
        - faradaytests
    extends:
        - .get-secrets
    image: python:3.11
    stage: pre_testing
    allow_failure: true
    script:
      - pip3 install virtualenv
      - virtualenv -p python3 faraday_venv
      - source faraday_venv/bin/activate
      - pip3 install bandit
      - mkdir /results
      - "bandit -r ${CI_PROJECT_DIR}/faraday -o /results/output.xml -f xml --skip B101,B202,B311,B501"
    after_script:
      - apt-get update -y
      - apt-get install -y wget ca-certificates libcap2-bin unzip
      - wget https://releases.hashicorp.com/vault/1.15.6/vault_1.15.6_linux_amd64.zip
      - unzip vault_1.15.6_linux_amd64.zip
      - mv vault /usr/sbin/vault
      - chmod +x /usr/sbin/vault
      - setcap cap_ipc_lock= /usr/sbin/vault
      - pip3 install faraday-cli
      - cat /results/output.xml
      - if [[ $(grep -c testcase /results/output.xml) -gt 0 ]]; then (faraday-cli auth -f $FARADAY_URL -u $FARADAY_USER -p $FARADAY_PASSWORD && faraday-cli workspace create $CI_COMMIT_REF_SLUG && faraday-cli tool report /results/output.xml -w $CI_COMMIT_REF_SLUG); else (echo 'no vulns dettected' && exit 0); fi
    rules:
        - !reference [ .ignore-on-tag, rules ]
        - when: on_success

ruff:
    image: python:3.11
    stage: pre_testing
    script:
      - pip install ruff
      - ruff check .
    rules:
        - !reference [ .ignore-on-tag, rules ]
        - when: on_success

no-format-str:
    image: python:3.11
    stage: pre_testing
    script:
      - pip install flynt==0.69
      - flynt -df faraday tests
    rules:
        - !reference [ .ignore-on-tag, rules ]
        - !reference [ .ignore-on-master, rules ]
        - when: on_success
