#!/usr/bin/env bash
#
# Create wrapper scripts for Faraday entry points
#
# Usage: ./create-wrapper-scripts.sh INSTALL_PREFIX
# Example: ./create-wrapper-scripts.sh /opt/faraday
#
# This script generates wrapper scripts that:
# - Use the bundled Python interpreter
# - Set environment variables (LD_LIBRARY_PATH)
# - Call the actual entry points from the venv
#

set -euo pipefail

INSTALL_PREFIX="${1:?ERROR: INSTALL_PREFIX required as first argument}"
VENV_BIN="${INSTALL_PREFIX}/venv/bin"
BUNDLED_PYTHON="${INSTALL_PREFIX}/python/bin/python3.11"
WRAPPER_DIR="${INSTALL_PREFIX}/bin"

echo "==> Creating wrapper scripts in ${WRAPPER_DIR}"

# Create wrapper directory
mkdir -p "${WRAPPER_DIR}"

# Entry points from pyproject.toml [project.scripts]
ENTRY_POINTS=(
    "faraday-server"
    "faraday-manage"
    "faraday-worker"
    "faraday-worker-gevent"
    "faraday-start-all"
)

for entry in "${ENTRY_POINTS[@]}"; do
    echo "==> Creating wrapper for ${entry}"

    cat > "${WRAPPER_DIR}/${entry}" <<'WRAPPER_EOF'
#!/bin/bash
# Wrapper script for ENTRY_POINT
# Auto-generated by create-wrapper-scripts.sh

# Determine installation directory (resolve symlinks)
SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
INSTALL_DIR="$(cd "$(dirname "$SCRIPT_PATH")/.." && pwd)"

# Set environment variables
export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:/usr/lib64:${LD_LIBRARY_PATH:-}"

# Execute the actual entry point from venv
exec "${INSTALL_DIR}/venv/bin/ENTRY_POINT" "$@"
WRAPPER_EOF

    # Replace placeholder with actual entry point name
    sed -i "s/ENTRY_POINT/${entry}/g" "${WRAPPER_DIR}/${entry}"

    # Make executable
    chmod +x "${WRAPPER_DIR}/${entry}"
done

echo "==> Successfully created ${#ENTRY_POINTS[@]} wrapper scripts"
echo "==> Wrapper scripts:"
ls -lh "${WRAPPER_DIR}"/faraday-*
