.get_from_tar_and_replace_www:
    script:
      - rm faraday/server/www
      - ls
      - tar xfvz faraday-frontend.tar.gz
      - mv build/ faraday/server/www/

generate_build_file_dev:
    image: registry.gitlab.com/faradaysec/devops
    stage: pre_build
    script:
        - "/bin/mkdir faraday_copy"
        - !reference [.get_from_tar_and_replace_www, script]
        - "/usr/bin/rsync -aq --exclude 'faraday_copy' --exclude '.cache' . faraday_copy"
        - "/bin/tar -zcf faraday.tar.gz faraday_copy"
    rules:
        - !reference [.be-built, rules]
        # What is not '/staging' is '/dev', '/master' or a development branch , and all are manual
        - !reference [.ignore-on-staging, rules]
        - !reference [.ignore-on-master, rules]
        - when: never
    artifacts:
        name: 'faraday'
        paths:
            - "faraday.tar.gz"
        expire_in: 15 days
    needs:
        - project: faradaysec/faraday-react
          job: npm_build
          ref: community/dev
          artifacts: true

generate_build_file_staging:
    image: registry.gitlab.com/faradaysec/devops
    stage: pre_build
    script:
        - "/bin/mkdir faraday_copy"
        - !reference [.get_from_tar_and_replace_www, script]
        - "/usr/bin/rsync -aq --exclude 'faraday_copy' --exclude '.cache' . faraday_copy"
        - "/bin/tar -zcf faraday.tar.gz faraday_copy"
    rules:
        - !reference [.on-staging, rules]
        - when: never
    artifacts:
        name: 'faraday'
        paths:
            - "faraday.tar.gz"
        expire_in: 15 days
    needs:
        - project: faradaysec/faraday-react
          job: npm_build
          ref: community/staging
          artifacts: true

generate_build_file_master:
    image: registry.gitlab.com/faradaysec/devops
    stage: pre_build
    script:
        - "/bin/mkdir faraday_copy"
        - !reference [.get_from_tar_and_replace_www, script]
        - "/usr/bin/rsync -aq --exclude 'faraday_copy' --exclude '.cache' . faraday_copy"
        - "/bin/tar -zcf faraday.tar.gz faraday_copy"
    rules:
        - !reference [.on-master, rules]
        - when: never
    artifacts:
        name: 'faraday'
        paths:
            - "faraday.tar.gz"
        expire_in: 15 days
    needs:
        - project: faradaysec/faraday-react
          job: npm_build
          ref: community/master
          artifacts: true

build_nix_python3_dev:
  image: nixorg/nix
  stage: pre_build
  tags:
    - digitalocean-dev
  script:
    - nix-env -if pynixify/nixpkgs.nix -A cachix gnugrep
    - nix-env -if pynixify/nixpkgs.nix -A vault
    - !reference [ .get_secrets, script ]
    - mkdir -p ~/.config/cachix
    - export USER=$(whoami)
    - echo "$CACHIX_CONFG" >~/.config/cachix/cachix.dhall
    - !reference [ .get_from_tar_and_replace_www, script ]
    - cachix use faradaysec
    - nix-build
    - tar cf /py3.tar $(nix-store --query --requisites $(readlink result))
    - mkdir -p /opt/faraday
    - cp -r $(readlink result)/* /opt/faraday
    - tar rvf /py3.tar /opt/faraday
    - mv /py3.tar $CI_PROJECT_DIR
  artifacts:
    name: python3
    paths:
      - py3.tar
    expire_in: 15 days # in the future we don't need to expire this.
  rules:
    - !reference [.be-built, rules]
    # What is not '/staging' is '/dev', '/master' or a development branch , and all are manual
    - !reference [.ignore-on-staging, rules]
    - !reference [.ignore-on-master, rules]
    - when: never
  needs:
    - project: faradaysec/faraday-react
      job: npm_build
      ref: community/dev
      artifacts: true

build_nix_python3_staging:
  image: nixorg/nix
  stage: pre_build
  tags:
    - digitalocean-dev
  script:
    - nix-env -if pynixify/nixpkgs.nix -A cachix gnugrep
    - nix-env -if pynixify/nixpkgs.nix -A vault
    - !reference [ .get_secrets, script ]
    - mkdir -p ~/.config/cachix
    - export USER=$(whoami)
    - echo "$CACHIX_CONFG" >~/.config/cachix/cachix.dhall
    - !reference [ .get_from_tar_and_replace_www, script ]
    - cachix use faradaysec
    - nix-build
    - tar cf /py3.tar $(nix-store --query --requisites $(readlink result))
    - mkdir -p /opt/faraday
    - cp -r $(readlink result)/* /opt/faraday
    - tar rvf /py3.tar /opt/faraday
    - mv /py3.tar $CI_PROJECT_DIR
  artifacts:
    name: python3
    paths:
      - py3.tar
    expire_in: 15 days # in the future we don't need to expire this.
  rules:
    - !reference [.on-staging, rules]
    - when: never
  needs:
    - project: faradaysec/faraday-react
      job: npm_build
      ref: community/staging
      artifacts: true

build_nix_python3_master:
  image: nixorg/nix
  stage: pre_build
  tags:
    - digitalocean-dev
  script:
    - nix-env -if pynixify/nixpkgs.nix -A cachix gnugrep
    - nix-env -if pynixify/nixpkgs.nix -A vault
    - !reference [ .get_secrets, script ]
    - mkdir -p ~/.config/cachix
    - export USER=$(whoami)
    - echo "$CACHIX_CONFG" >~/.config/cachix/cachix.dhall
    - !reference [ .get_from_tar_and_replace_www, script ]
    - cachix use faradaysec
    - nix-build
    - tar cf /py3.tar $(nix-store --query --requisites $(readlink result))
    - mkdir -p /opt/faraday
    - cp -r $(readlink result)/* /opt/faraday
    - tar rvf /py3.tar /opt/faraday
    - mv /py3.tar $CI_PROJECT_DIR
  artifacts:
    name: python3
    paths:
      - py3.tar
    expire_in: 15 days # in the future we don't need to expire this.
  rules:
    - !reference [.on-master, rules]
    - when: never
  needs:
    - project: faradaysec/faraday-react
      job: npm_build
      ref: community/master
      artifacts: true
