#!/usr/bin/env python3
"""
Claude-powered GitLab MR reviewer.

Manual-triggered GitLab CI job. Collects the MR diff, asks Claude for
structured review comments, and posts them as inline discussions + a
summary note on the MR. Runs on any MR state (including Draft) — the
manual-trigger gate is the human control point.

Exit codes: 0 on success or legitimate no-op (no MR, no reviewable changes,
no new commits since prior review). Non-zero on real failures (env error,
MR lookup error, fatal exception) so the CI job surfaces the problem.

Required env vars (all provided by GitLab CI + .get-secrets):
  ANTHROPIC_API_KEY
  GITLAB_REVIEW_TOKEN          project access token with `api` scope
  CI_API_V4_URL                e.g. https://gitlab.com/api/v4
  CI_PROJECT_ID
  CI_MERGE_REQUEST_IID
  CI_MERGE_REQUEST_DIFF_BASE_SHA
  CI_COMMIT_SHA
Optional:
  CLAUDE_MODEL                 default: claude-sonnet-4-6
"""

from __future__ import annotations

import hashlib
import os
import re
import subprocess
import sys
import time
from dataclasses import dataclass
from typing import Any

import requests
from anthropic import (
    Anthropic,
    APIConnectionError,
    APIStatusError,
    APITimeoutError,
    RateLimitError,
)

DEFAULT_MODEL = "claude-sonnet-4-6"
RESPONSE_TOKEN_BUDGET = 8000
DEFAULT_THINKING_BUDGET = 8000
MAX_INPUT_CHARS_PER_CHUNK = 280_000  # rough proxy for ~80k input tokens
MAX_FILE_DIFF_LINES = 1500
SKIP_PATH_SUFFIXES = (
    # Minified / source maps
    ".min.js", ".min.css", ".map",
    # Lock files
    "uv.lock", "package-lock.json", "poetry.lock", "yarn.lock",
    "Pipfile.lock", "Cargo.lock", "composer.lock",
    # Compiled / bytecode
    ".pyc", ".pyo", ".pyd",
    # Native libraries
    ".so", ".dylib", ".dll",
    # Archives / packages
    ".whl", ".egg", ".tar.gz", ".tgz", ".zip", ".gz", ".bz2", ".xz", ".7z",
    # Images
    ".png", ".jpg", ".jpeg", ".gif", ".ico", ".webp", ".svg", ".pdf",
    ".bmp", ".tiff",
    # Fonts
    ".woff", ".woff2", ".ttf", ".eot", ".otf",
    # Translations / compiled locales
    ".mo", ".pot",
    # Test snapshots
    ".snap", ".snapshot",
    # Generated API specs (faraday: autogenerated from code)
    "faraday_swagger.json",
    # Release notes (auto-compiled from CHANGELOG/current)
    "RELEASE.md",
)
SKIP_PATH_CONTAINS = (
    "vendor/", "node_modules/", "dist/", "build/",
    # Test fixtures: scan reports, sample CSVs, example XML, etc.
    "tests/data/",
    # IDE workspaces that occasionally slip into commits
    ".idea/", ".vscode/",
)

SYSTEM_PROMPT = """You are a senior code reviewer for Faraday, a Python-based
security platform. Review the attached MR diff and return findings via emit_review.

DIFF FORMAT — every line carries its NEW-file line number as a prefix:
  "  123: + added"       added line, file line 123
  "  123:   context"     context line, file line 123
  "     : - removed"     removed line, no new-file number
The `line` field in each inline comment MUST be copied verbatim from the
prefix. Never count, infer, or comment inline on removed-only lines —put those observations in the summary instead.

APPROACH — two phases before emitting:

  1. SCAN. Enumerate every candidate concern across:
     • Correctness — logic bugs, off-by-one, wrong operator, swallowed
       errors, missing boundary error handling, broken invariants.
     • Security — auth bypass, injection (SQL/shell/template), unsafe
       deserialization, SSRF, path traversal, secret leakage, unsafe
       crypto, TOCTOU.
     • Data integrity — migrations, schema drift, index/query changes,
       breaking contract or API changes.
     • Maintainability — dead code, duplication, misleading names —
       only if clearly shown in the diff.

  2. FILTER. For each candidate: present in the diff? actionable?
     severity high (bug/risk), medium (likely issue), or low (nit)?
     Drop speculative or non-actionable items.

EMIT — call emit_review exactly once:
  • Every high and medium finding becomes an inline comment. Do not sample.
  • Every low finding goes in the summary.
  • File path exactly as shown in the "===== FILE: <path> =====" header.
  • Body: one-sentence problem, one-sentence fix, optional one line of
    code. No preamble, no restating the code.

If nothing is high or medium, emit zero comments plus a short summary
saying so. If unsure about any single item, skip it — do not hallucinate."""

EMIT_REVIEW_TOOL = {
    "name": "emit_review",
    "description": "Emit structured review output for the MR diff.",
    "input_schema": {
        "type": "object",
        "properties": {
            "comments": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "file": {"type": "string"},
                        "line": {"type": "integer"},
                        "severity": {"enum": ["low", "medium", "high"]},
                        "body": {"type": "string"},
                    },
                    "required": ["file", "line", "severity", "body"],
                },
            },
            "summary": {"type": "string"},
        },
        "required": ["comments", "summary"],
    },
}


@dataclass
class Env:
    anthropic_key: str
    gitlab_token: str
    api_url: str
    project_id: str
    mr_iid: str
    base_sha: str
    head_sha: str
    model: str


def _resolve_secret(value: str) -> str:
    """GitLab Vault secrets default to file-based since 15.7 — the env var
    holds a path to a file containing the actual value. Handle both forms."""
    if value and os.path.isfile(value):
        with open(value) as f:
            return f.read().strip()
    return value.strip() if value else value


def load_env() -> Env:
    required = [
        "ANTHROPIC_API_KEY",
        "GITLAB_REVIEW_TOKEN",
        "CI_API_V4_URL",
        "CI_PROJECT_ID",
        "CI_MERGE_REQUEST_IID",
        "CI_MERGE_REQUEST_DIFF_BASE_SHA",
        "CI_COMMIT_SHA",
    ]
    missing = [k for k in required if not os.environ.get(k)]
    if missing:
        raise RuntimeError(f"missing env vars: {', '.join(missing)}")
    return Env(
        anthropic_key=_resolve_secret(os.environ["ANTHROPIC_API_KEY"]),
        gitlab_token=_resolve_secret(os.environ["GITLAB_REVIEW_TOKEN"]),
        api_url=os.environ["CI_API_V4_URL"].rstrip("/"),
        project_id=os.environ["CI_PROJECT_ID"],
        mr_iid=os.environ["CI_MERGE_REQUEST_IID"],
        base_sha=os.environ["CI_MERGE_REQUEST_DIFF_BASE_SHA"],
        head_sha=os.environ["CI_COMMIT_SHA"],
        model=os.environ.get("CLAUDE_MODEL", DEFAULT_MODEL),
    )


def git(*args: str) -> str:
    out = subprocess.run(
        ["git", *args],
        check=True,
        capture_output=True,
        text=True,
    )
    return out.stdout


def should_skip_path(path: str) -> bool:
    if any(path.endswith(s) for s in SKIP_PATH_SUFFIXES):
        return True
    if any(s in path for s in SKIP_PATH_CONTAINS):
        return True
    return False


HUNK_HEADER_RE = re.compile(r"^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@")


def annotate_patch(patch: str) -> str:
    """Prepend each diff line with its NEW-file line number so the model
    cannot confuse diff-local offsets with file line numbers.

    Added / context lines: "  123: + added" / "  123:   context"
    Removed lines:         "     : - removed"
    Headers are left unchanged.
    """
    out: list[str] = []
    new_line: int | None = None
    for line in patch.splitlines():
        if line.startswith("@@"):
            m = HUNK_HEADER_RE.match(line)
            new_line = int(m.group(1)) if m else None
            out.append(line)
            continue
        if line.startswith(("diff ", "index ", "--- ", "+++ ", "new file ",
                            "deleted file ", "rename ", "similarity ",
                            "Binary ")):
            out.append(line)
            continue
        if new_line is None:
            out.append(line)
            continue
        if line.startswith("+") and not line.startswith("+++"):
            out.append(f"{new_line:5d}: {line}")
            new_line += 1
        elif line.startswith("-") and not line.startswith("---"):
            out.append(f"     : {line}")
        elif line.startswith(" "):
            out.append(f"{new_line:5d}: {line}")
            new_line += 1
        else:
            # Empty strings or any other shape: pass through without
            # advancing the line counter so a malformed input can't shift
            # numbering for the rest of the hunk.
            out.append(line)
    return "\n".join(out)


def _parse_numstat_z(raw: str) -> list[tuple[str, str, str]]:
    """Parse `git diff --numstat -z` output into (added, removed, new_path) tuples.

    Format per git: normal entries are ``added\\tremoved\\tpath\\0``;
    rename/copy entries are ``added\\tremoved\\t\\0oldpath\\0newpath\\0``.
    NUL terminates each logical entry.
    """
    entries: list[tuple[str, str, str]] = []
    parts = raw.split("\0")
    i = 0
    while i < len(parts):
        piece = parts[i]
        if not piece:
            i += 1
            continue
        fields = piece.split("\t", 2)
        if len(fields) < 3:
            i += 1
            continue
        added, removed, path = fields
        if path == "":
            # rename/copy: next two NUL-separated parts are oldpath, newpath
            if i + 2 >= len(parts):
                break
            newpath = parts[i + 2]
            entries.append((added, removed, newpath))
            i += 3
        else:
            entries.append((added, removed, path))
            i += 1
    return entries


def collect_diff(
    env: Env, base_override: str | None = None,
) -> tuple[list[tuple[str, str]], list[str]]:
    """Return ``(diffs, size_skipped)``.

    ``diffs`` is a list of ``(file_path, annotated_patch)`` for reviewable
    files. ``size_skipped`` is a list of ``"path (reason)"`` strings for
    files whose size prevents review — these are surfaced in the MR
    summary so the author knows the file wasn't ignored silently. Binary
    and generated/vendored skips are policy and stay stdout-only.

    ``base_override`` lets an incremental run diff from a prior review's
    commit rather than the MR base.
    """
    base = base_override or env.base_sha
    numstat = git("diff", "--numstat", "-z", f"{base}..{env.head_sha}")
    reviewable: list[str] = []
    skipped_policy: list[str] = []
    size_skipped: list[str] = []
    for added, removed, path in _parse_numstat_z(numstat):
        if added == "-" and removed == "-":
            skipped_policy.append(f"{path} (binary)")
            continue
        if should_skip_path(path):
            skipped_policy.append(f"{path} (generated/vendored)")
            continue
        try:
            total = int(added) + int(removed)
        except ValueError:
            print(
                f"[claude-review] skipping {path}: malformed numstat "
                f"(added={added!r}, removed={removed!r})",
                file=sys.stderr,
            )
            continue
        if total > MAX_FILE_DIFF_LINES:
            size_skipped.append(f"{path} ({total} lines, > {MAX_FILE_DIFF_LINES})")
            continue
        reviewable.append(path)

    if skipped_policy:
        print("[claude-review] skipped (policy):")
        for n in skipped_policy:
            print(f"  - {n}")

    diffs: list[tuple[str, str]] = []
    for path in reviewable:
        patch = git(
            "diff",
            "--no-color",
            f"{base}..{env.head_sha}",
            "--",
            path,
        )
        if not patch.strip():
            continue
        annotated = annotate_patch(patch)
        # Single-file block must fit in a chunk on its own.
        if len(annotated) > MAX_INPUT_CHARS_PER_CHUNK:
            size_skipped.append(
                f"{path} (annotated diff {len(annotated)} chars, "
                f"> {MAX_INPUT_CHARS_PER_CHUNK})"
            )
            continue
        diffs.append((path, annotated))

    if size_skipped:
        print("[claude-review] skipped (too large):")
        for n in size_skipped:
            print(f"  - {n}")

    return diffs, size_skipped


def chunk_diffs(diffs: list[tuple[str, str]]) -> list[str]:
    chunks: list[str] = []
    current: list[str] = []
    current_size = 0
    for path, patch in diffs:
        block = f"\n\n===== FILE: {path} =====\n{patch}"
        if current_size + len(block) > MAX_INPUT_CHARS_PER_CHUNK and current:
            chunks.append("".join(current))
            current = []
            current_size = 0
        current.append(block)
        current_size += len(block)
    if current:
        chunks.append("".join(current))
    return chunks


def call_claude(
    client: Anthropic,
    model: str,
    chunk: str,
    prior_summary: str | None = None,
) -> dict[str, Any]:
    lead = (
        "Review the following MR diff. Do a Phase 1 scan and Phase 2 filter "
        "as specified in your instructions, then respond via the emit_review "
        "tool.\n"
    )
    if prior_summary:
        lead += (
            "\nA previous Claude review ran on an earlier commit of this same "
            "MR. Its summary is below, for context. The diff you are reviewing "
            "now covers ONLY the commits added since that prior review. Do not "
            "re-raise items already listed in the prior summary unless they "
            "are still applicable to the new changes.\n\n"
            "=== PREVIOUS REVIEW SUMMARY ===\n"
            + prior_summary.strip()
            + "\n=== END PREVIOUS REVIEW SUMMARY ===\n\n"
        )
    user_msg = lead + chunk
    thinking_budget = max(0, int(os.environ.get(
        "CLAUDE_THINKING_BUDGET", DEFAULT_THINKING_BUDGET
    )))
    kwargs: dict[str, Any] = dict(
        model=model,
        max_tokens=thinking_budget + RESPONSE_TOKEN_BUDGET,
        system=SYSTEM_PROMPT,
        tools=[EMIT_REVIEW_TOOL],
        # Extended thinking disallows any form of forced tool use. `auto`
        # lets Claude choose — with one tool defined and the system prompt
        # explicitly instructing to call it, this reliably triggers it.
        tool_choice={"type": "auto"},
        messages=[{"role": "user", "content": user_msg}],
    )
    if thinking_budget > 0:
        kwargs["thinking"] = {
            "type": "enabled",
            "budget_tokens": thinking_budget,
        }
    attempt = 0
    while True:
        attempt += 1
        try:
            resp = client.messages.create(**kwargs)
        except (APIConnectionError, APITimeoutError):
            if attempt >= 3:
                raise
            time.sleep(2 ** attempt)
            continue
        except (RateLimitError, APIStatusError) as exc:
            status = getattr(exc, "status_code", None)
            if attempt >= 3 or (status and status < 500 and status not in (408, 429)):
                raise
            time.sleep(2 ** attempt)
            continue
        merged_comments: list[Any] = []
        merged_summaries: list[str] = []
        for block in resp.content:
            if block.type != "tool_use" or block.name != "emit_review":
                continue
            inp = block.input or {}
            comments = inp.get("comments")
            if isinstance(comments, list):
                merged_comments.extend(comments)
            summary = inp.get("summary")
            if isinstance(summary, str) and summary.strip():
                merged_summaries.append(summary.strip())
        if not merged_comments and not merged_summaries:
            return {
                "comments": [],
                "summary": "(model returned no structured output)",
            }
        return {
            "comments": merged_comments,
            "summary": "\n\n".join(merged_summaries),
        }


SEVERITY_BADGE = {
    "high": "High severity",
    "medium": "Medium severity",
    "low": "Low severity",
}


def marker(head_sha: str) -> str:
    return f"<!-- claude-review:{head_sha[:12]} -->"


def hidden_meta(env: Env, fingerprint: str | None = None) -> str:
    """Invisible HTML-comment footer carrying the markers used for dedupe."""
    parts = [marker(env.head_sha)]
    if fingerprint:
        parts.append(f"<!-- fp:{fingerprint} -->")
    return "\n\n" + " ".join(parts)


def gitlab_headers(env: Env) -> dict[str, str]:
    return {"PRIVATE-TOKEN": env.gitlab_token}


def comment_fingerprint(c: dict[str, Any]) -> str:
    raw = f"{c['file']}|{c['line']}|{c['body']}"
    return hashlib.sha256(raw.encode()).hexdigest()[:10]


def _valid_comment(c: Any) -> bool:
    if not isinstance(c, dict):
        return False
    file_ = c.get("file")
    line = c.get("line")
    body = c.get("body")
    return (
        isinstance(file_, str) and file_ != ""
        # bool is a subclass of int — exclude it explicitly.
        and isinstance(line, int) and not isinstance(line, bool) and line > 0
        and isinstance(body, str) and body.strip() != ""
        and c.get("severity") in ("low", "medium", "high")
    )


def post_inline(env: Env, comment: dict[str, Any]) -> str:
    """Post a review comment. Returns 'inline', 'fallback', or 'failed'."""
    url = f"{env.api_url}/projects/{env.project_id}/merge_requests/{env.mr_iid}/discussions"
    badge = SEVERITY_BADGE.get(comment["severity"], comment["severity"].title())
    body = (
        f"**Claude review** · {badge}\n\n"
        f"{comment['body']}"
        f"{hidden_meta(env, comment_fingerprint(comment))}"
    )
    data = {
        "body": body,
        "position[base_sha]": env.base_sha,
        "position[start_sha]": env.base_sha,
        "position[head_sha]": env.head_sha,
        "position[position_type]": "text",
        "position[new_path]": comment["file"],
        "position[new_line]": comment["line"],
    }
    r = requests.post(url, headers=gitlab_headers(env), data=data, timeout=30)
    if r.status_code in (200, 201):
        return "inline"
    print(f"[claude-review] inline post failed ({r.status_code}) for "
          f"{comment['file']}:{comment['line']} — falling back to note")
    try:
        post_note(
            env,
            f"**Claude review** · {badge} · `{comment['file']}:{comment['line']}`\n\n"
            f"{comment['body']}",
        )
        return "fallback"
    except requests.RequestException as exc:
        print(f"[claude-review] fallback note failed: {exc}", file=sys.stderr)
        return "failed"


def post_note(env: Env, body: str) -> None:
    url = f"{env.api_url}/projects/{env.project_id}/merge_requests/{env.mr_iid}/notes"
    full = f"{body}{hidden_meta(env)}"
    r = requests.post(
        url, headers=gitlab_headers(env), data={"body": full}, timeout=30,
    )
    r.raise_for_status()


def _populate_mr_env_from_branch() -> bool:
    """When running on a branch pipeline (no MR context set), look up the
    open MR for CI_COMMIT_REF_NAME and populate the MR env vars in-place.

    Returns True if an MR was found and env is populated, False if no open
    MR matches the source branch.
    """
    token = _resolve_secret(os.environ.get("GITLAB_REVIEW_TOKEN", ""))
    api_url = os.environ.get("CI_API_V4_URL", "").rstrip("/")
    project_id = os.environ.get("CI_PROJECT_ID", "")
    branch = os.environ.get("CI_COMMIT_REF_NAME", "")
    missing = [k for k, v in {
        "GITLAB_REVIEW_TOKEN": token,
        "CI_API_V4_URL": api_url,
        "CI_PROJECT_ID": project_id,
        "CI_COMMIT_REF_NAME": branch,
    }.items() if not v]
    if missing:
        raise RuntimeError(f"MR lookup missing env: {', '.join(missing)}")

    headers = {"PRIVATE-TOKEN": token}
    r = requests.get(
        f"{api_url}/projects/{project_id}/merge_requests",
        headers=headers,
        params={
            "state": "opened",
            "source_branch": branch,
            "order_by": "created_at",
            "sort": "desc",
            "per_page": 1,
        },
        timeout=30,
    )
    r.raise_for_status()
    mrs = r.json()
    if not mrs:
        return False

    iid = mrs[0]["iid"]
    # Fetch detail to guarantee diff_refs are present.
    d = requests.get(
        f"{api_url}/projects/{project_id}/merge_requests/{iid}",
        headers=headers,
        timeout=30,
    )
    d.raise_for_status()
    full = d.json()
    diff_refs = full.get("diff_refs") or {}
    base_sha = diff_refs.get("base_sha")
    if not base_sha:
        raise RuntimeError(f"MR !{iid} has no diff_refs.base_sha")

    os.environ["CI_MERGE_REQUEST_IID"] = str(iid)
    os.environ["CI_MERGE_REQUEST_DIFF_BASE_SHA"] = base_sha
    print(f"[claude-review] resolved MR !{iid} for branch {branch!r}")
    return True


def _ensure_commits_fetched(base_sha: str, head_sha: str) -> None:
    """Best-effort fetch of the two SHAs in case the runner did a shallow clone."""
    subprocess.run(
        ["git", "fetch", "--no-tags", "origin", base_sha, head_sha],
        check=False, capture_output=True, text=True,
    )


def _git_has_commit(sha: str) -> bool:
    """True if the commit is reachable in the local repository."""
    r = subprocess.run(
        ["git", "cat-file", "-e", sha],
        capture_output=True, text=True,
    )
    return r.returncode == 0


_PRIOR_MARKER_RE = re.compile(r"<!-- claude-review:([0-9a-f]{12}) -->")
_OVERVIEW_HEADER_RE = re.compile(r"^### Overview\s*$", re.MULTILINE)
_NEXT_SECTION_RE = re.compile(r"^### \S", re.MULTILINE)


def _extract_overview(body: str) -> str:
    """Pull the `### Overview` section out of a prior summary note.

    Returns just the prose under that header, dropping the meta line, the
    counts table, the Nits list, the Skipped list, and the hidden
    markers. If the header isn't present the prior summary likely had no
    overview content, so return an empty string rather than feeding the
    full noisy body back to the model.
    """
    if not body:
        return ""
    m = _OVERVIEW_HEADER_RE.search(body)
    if not m:
        return ""
    rest = body[m.end():]
    nxt = _NEXT_SECTION_RE.search(rest)
    section = rest[:nxt.start()] if nxt else rest
    return section.strip()


def _prior_sha_from_body(body: str) -> str | None:
    """Extract the commit sha12 from the hidden marker in a summary note body."""
    m = _PRIOR_MARKER_RE.search(body or "")
    return m.group(1) if m else None


def _find_last_review(env: Env) -> dict[str, Any] | None:
    """Return the newest prior-review *summary* note on this MR, or None.

    Identified by BOTH the `<!-- claude-review:{sha12} -->` marker and the
    `## Claude review` header. The header excludes inline-fallback notes
    (those use a different heading) so we only latch on to actual summaries.
    """
    url = f"{env.api_url}/projects/{env.project_id}/merge_requests/{env.mr_iid}/notes"
    max_pages = 20  # cap: 2000 notes is far beyond any realistic MR
    for page in range(1, max_pages + 1):
        r = requests.get(
            url,
            headers=gitlab_headers(env),
            params={
                "per_page": 100,
                "page": page,
                "sort": "desc",
                "order_by": "created_at",
            },
            timeout=30,
        )
        r.raise_for_status()
        batch = r.json()
        if not batch:
            return None
        for n in batch:
            body = n.get("body", "")
            if "<!-- claude-review:" in body and "## Claude review" in body:
                return n
        if len(batch) < 100:
            return None
    return None


def main() -> int:
    # Branch pipelines have no MR env; resolve the MR from the source branch.
    if not os.environ.get("CI_MERGE_REQUEST_IID"):
        try:
            found = _populate_mr_env_from_branch()
        except Exception as exc:
            print(f"[claude-review] MR lookup error: {exc}", file=sys.stderr)
            return 1
        if not found:
            branch = os.environ.get("CI_COMMIT_REF_NAME", "?")
            print(f"[claude-review] no open MR for branch {branch!r}, nothing to review")
            return 0

    try:
        env = load_env()
    except Exception as exc:
        print(f"[claude-review] env error: {exc}", file=sys.stderr)
        return 1

    _ensure_commits_fetched(env.base_sha, env.head_sha)

    try:
        # Incremental review: if a prior summary exists, diff from that SHA
        # instead of the MR base, and pass its body to Claude for context.
        prior_sha: str | None = None
        prior_summary: str | None = None
        prior = _find_last_review(env)
        if prior is not None:
            prior_sha_short = _prior_sha_from_body(prior.get("body", ""))
            if prior_sha_short:
                # No pre-fetch for prior_sha_short: git remotes can't be
                # queried by abbreviated SHA, and GIT_DEPTH=0 in CI yaml
                # means the runner already has full history.
                if _git_has_commit(prior_sha_short):
                    if prior_sha_short == env.head_sha[:12]:
                        post_note(
                            env,
                            "_No new commits since the previous Claude review._",
                        )
                        return 0
                    prior_sha = prior_sha_short
                    # Strip everything but the Overview prose — the meta
                    # line, counts table, Nits and Skipped sections, and
                    # hidden markers are noise that hurts model focus.
                    prior_summary = _extract_overview(prior.get("body") or "") or None
                    print(
                        f"[claude-review] incremental review since {prior_sha} "
                        f"(prior note #{prior.get('id')})"
                    )
                else:
                    print(
                        f"[claude-review] prior review SHA {prior_sha_short} "
                        f"not reachable locally — falling back to full diff"
                    )

        diffs, size_skipped = collect_diff(env, base_override=prior_sha)
        if not diffs:
            scope = (
                f"since the previous Claude review (`{prior_sha}`)"
                if prior_sha else "in this MR"
            )
            if size_skipped:
                lines = [f"_No reviewable changes {scope} — all candidate "
                         f"files exceeded size limits:_", ""]
                lines += [f"- `{n}`" for n in size_skipped]
                post_note(env, "\n".join(lines))
            else:
                post_note(env, f"_No reviewable changes {scope}._")
            return 0

        total_chars = sum(len(p) for _, p in diffs)
        print(f"[claude-review] {len(diffs)} files, ~{total_chars} chars, "
              f"model={env.model}")

        chunks = chunk_diffs(diffs)
        client = Anthropic(api_key=env.anthropic_key)

        all_comments: list[dict[str, Any]] = []
        summaries: list[str] = []
        for i, chunk in enumerate(chunks, 1):
            print(f"[claude-review] chunk {i}/{len(chunks)} "
                  f"({len(chunk)} chars)")
            # Prior summary is context, not per-chunk input — send on first chunk only.
            result = call_claude(
                client, env.model, chunk,
                prior_summary=prior_summary if i == 1 else None,
            )
            all_comments.extend(result.get("comments", []))
            s = result.get("summary", "").strip()
            if s:
                summaries.append(s)

        # drop malformed entries from the model
        valid_comments: list[dict[str, Any]] = []
        for c in all_comments:
            if _valid_comment(c):
                valid_comments.append(c)
            else:
                print(f"[claude-review] dropping malformed comment: {c!r}",
                      file=sys.stderr)

        # dedupe within this run
        seen: set[str] = set()
        unique: list[dict[str, Any]] = []
        for c in valid_comments:
            fp = comment_fingerprint(c)
            if fp in seen:
                continue
            seen.add(fp)
            unique.append(c)

        inline = [c for c in unique if c["severity"] in ("medium", "high")]
        low_notes = [c for c in unique if c["severity"] == "low"]

        inline_count = 0
        fallback_count = 0
        for c in inline:
            try:
                result = post_inline(env, c)
            except requests.RequestException as exc:
                print(f"[claude-review] post error: {exc}", file=sys.stderr)
                continue
            if result == "inline":
                inline_count += 1
            elif result == "fallback":
                fallback_count += 1

        meta_line = (
            f"**Model** `{env.model}` · **Commit** `{env.head_sha[:12]}`"
        )
        if prior_sha:
            meta_line += f" · **Incremental since** `{prior_sha}`"
        summary_lines = [
            "## Claude review",
            "",
            meta_line,
            "",
            f"| Inline | Fallback | Nits |",
            f"| ---: | ---: | ---: |",
            f"| {inline_count} | {fallback_count} | {len(low_notes)} |",
        ]
        if summaries:
            summary_lines += ["", "### Overview", *summaries]
        if low_notes:
            summary_lines += ["", "### Nits"]
            for c in low_notes:
                summary_lines.append(
                    f"- `{c['file']}:{c['line']}` — {c['body']}"
                )
        if size_skipped:
            summary_lines += ["", "### Skipped (too large)"]
            for n in size_skipped:
                summary_lines.append(f"- `{n}`")
        post_note(env, "\n".join(summary_lines))
        return 0

    except Exception as exc:
        print(f"[claude-review] fatal: {exc}", file=sys.stderr)
        try:
            post_note(
                env,
                f"_Claude review failed: `{type(exc).__name__}`. "
                f"See job log for details._",
            )
        except Exception:
            pass
        return 1


if __name__ == "__main__":
    sys.exit(main())
